### ISSUE TITLE
If I use import LajiForm from "laji-form/lib/components/LajiForm" i keep getting window error

### ISSUE THREAD

**Issue by PoojaRayC** [luomus/laji-form#4]
UncaughtException err=ReferenceError: window is not defined

I have a basic requirement , passing the schema details and return the <LajiForm> but keep getting this compile error

**Comment by olzraiti** [comment]
Are you in a headless environment? E.g. node environment, not in a browser? LajiForm has never been planned to be used in such environment, but I could merge a PR if you want to make it work.

**Comment by olzraiti** [comment]
Yes, use `renderSubmit={false}`
